namespace SettlersOfIdlestan.Model.Tasks;

public enum TutorialTaskId
{
    Harvest5Wood,
    Harvest5Brick,
    BuildSeaport,
    BuildSawmill,
    BuildBrickworks,
    BuildFirstRoad,
    Harvest15Food,
    BuildSecondCity,
    UpgradeProductionBuildingsLevel2,
    Build10Cities,
    Build5Libraries,
    Build5Palisades,
    SeaportAndTownHallLevel4SameCity,
    SeaportLevel4,
    TownHallLevel4,
    BuildImperialPort,
    Build2Warehouses,
    Build1Warehouse,
    Trade10Gold,
    Build3Warehouses,
    Reach20VictoryPoints,
    PerformPrestige,
    Reach30VictoryPoints,
    BuyResearchVertex,
    CompleteFirstResearch,
    BuildLibraryLevel2,
}
